# Generated by Django 4.0 on 2022-01-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_rename_studentemail_student_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=True),
        ),
    ]
